# Generated by Django 5.2.5 on 2025-08-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domestique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='task_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when the task should be performed', null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
    ]
